### ISSUE TITLE
Mutation testing (and reporting) across Maven modules

### ISSUE THREAD

**Issue by AssafKatz3** [STAMP-project/pitmp-maven-plugin#9] opened 2018-04-23 05:50 UTC
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: crash
- **Tool/Service/Component**: pitmp-maven-plugin, 1.1.4
- **Execution Environment**: Java 1.8, Linux
- **Reporter**: Assaf Katz, assafkatz3@gmail.com

#### Description
Getting NullPointerException on PmpMojo.updateTargetClasses.

#### Steps to reproduce
Create main project with following modules:
* persistent:
   * src/java
* service:
   * src/java
* tests:
   * src/test (JUnit)

Add to main pom.xml (build section):

>           <plugin>
>             <groupId>eu.stamp-project</groupId>
>             <artifactId>pitmp-maven-plugin</artifactId>
>             <version>1.1.4</version>
>             <dependencies>
>               <dependency>
>                     <groupId>org.pitest</groupId>
>                     <artifactId>pitest-maven</artifactId>
>                     <version>1.3.2</version>
>               </dependency>
>             </dependencies>
>           </plugin>
 

Run mvn org.pitest:pitest-maven:mutationCoverage.

#### Other files and URLs
None.

#### Relationships
[Mutation testing (and reporting) across Maven modules #376](https://github.com/hcoles/pitest/issues/376#issuecomment-383405148)

**Comment by oscarlvp** [comment] 2018-04-23 07:50
Could this be a duplicate of #6?

**Comment by AssafKatz3** [comment] 2018-04-23 08:35
@oscarlvp This seems to be use case of #6

**Comment by Cael35** [comment] 2018-04-23 21:55
Hello @AssafKatz3,
Duplicate #6 
This issue is fixed in the release 1.1.5 available in Maven Central.
Unfortunately there is still a bug: if you don't specify any targetClass, no mutation are found. I created an issue for it (#10).

**Closed as completed by Cael35** 2018-04-23 21:55 UTC
